---
title: "Batch correction and data set integration"
subtitle: "03_Integration_Harmony"
author: "SarahL."
date: "`r format(Sys.time(), '%b %e %Y %H:%M:%S')`"
output: 
  html_document:
    toc: true
    number_sections: true   
    toc_float: true
    code_folding: hide
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Batch correction and data set integration

## Setup

### Load Packages

```{r LoadPackages, warning=FALSE}
#Load Packages

suppressPackageStartupMessages({
library(BiocParallel)
library(ggplot2)
library(dplyr)
library(scater)
library(scran)
library(batchelor)
library(reticulate)
library(bluster)
})

```

### Set params

```{r Setup}
set.seed(100)
bpp <- BiocParallel::MulticoreParam(parallel::detectCores()-1)
path <- "/Volumes/Elements/Masterthesis/RA_SingleCellAnalysis/"
```


## Load Data

```{r LoadDataset}
## RA DATASET
sce.filtered <- readRDS(file = paste0(path,'output/02_sce_DimensionalityReduction.rds'))

```


### Explore dataset

```{r ShowDim}
#Dimensions of count matrix
dim(sce)
```

## Pre-batch correction plots

```{r}
#Plot UMAP before data integration
plotReducedDim(sce, dimred="PCA", colour_by="Sample") #+ facet_wrap(~sce.filtered$Sample)
plotReducedDim(sce, dimred="UMAP", colour_by="Sample")
```

## Batch removal

```{r}
#Initialize sce element with batch removal
sce.BatchR <- sce 

```

### Batch removal with batchelor package

```{r}
#Perform scaling normalization within each batch

meta_data <- colData(sce.BatchR) %>%
  as.data.frame() %>%
  dplyr::select(c(Sample)) #Add covariates zb protocol

sce.BatchR <- harmony::RunHarmony(sce.BatchR,group.by.vars=c("Sample"),reduction.save="harmony",verbose=FALSE) #  Add covariates zb protocol


#Run UMAP
sce.BatchR <- runUMAP(sce.BatchR, dimred="harmony", subset_row=rowData(sce)$is_hvg, min_dist = 0.1, name="harmony_UMAP_extra")
sce.BatchR <- runUMAP(sce.BatchR, dimred="harmony", name="harmony_UMAP")

```

### QC plots harmony

```{r}
#We use the percentage of variance lost as a diagnostic measure:
metadata(sce.BatchR)$merge.info$lost.var

#Large proportions of lost variance (>10%) suggest that correction is removing genuine biological heterogeneity
```

## PCA and UMAP Plots after Integration

```{r}
#Plot PCA before data integration
plotReducedDim(sce.BatchR, dimred="PCA", colour_by="Sample") + ggtitle("PCA before data integration")
plotReducedDim(sce.BatchR, dimred="PCA", colour_by="JointLocation") + ggtitle("PCA before data integration")

#Plot PCA after data integration
plotReducedDim(sce.BatchR, dimred="harmony", colour_by="Sample") + ggtitle("PCA after data integration with harmony")
plotReducedDim(sce.BatchR, dimred="harmony", colour_by="JointLocation") + ggtitle("PCA after data integration with harmony")#+ facet_wrap(~sce.filtered$Sample)


#Plot PCA after data integration per sample
plotReducedDim(sce.BatchR, dimred="harmony", colour_by="Sample") + ggtitle("PCA after data integration with harmony")+ facet_wrap(~sce.BatchR$Sample)
#ggcells(sce.BatchR, aes(x = MNN_UMAP.1, y = MNN_UMAP.2, colour = Sample)) +geom_point(size = 0.5) +facet_wrap(~ Sample) +labs(x = "PC1", y = "PC2", colour = "Sample")

#Plot PCA after data integration per joint
plotReducedDim(sce.BatchR, dimred="harmony", colour_by="JointLocation") + ggtitle("PCA after data integration with harmony")+ facet_wrap(~sce.BatchR$JointLocation)

```

```{r}
#Plot UMAP before data integration
plotReducedDim(sce.BatchR, dimred="UMAP", colour_by="Sample") + ggtitle("UMAP before data integration")
plotReducedDim(sce.BatchR, dimred="UMAP", colour_by="JointLocation") + ggtitle("UMAP before data integration")

#Plot UMAP after data integration
plotReducedDim(sce.BatchR, dimred="harmony_UMAP", colour_by="Sample") + ggtitle("UMAP after data integration with harmony")
plotReducedDim(sce.BatchR, dimred="harmony_UMAP", colour_by="JointLocation") + ggtitle("UMAP after data integration with harmony")#+ facet_wrap(~sce.filtered$Sample)

#Plot UMAP after data integration per sample
plotReducedDim(sce.BatchR, dimred="harmony_UMAP", colour_by="Sample") + ggtitle("UMAP after data integration with harmony")+ facet_wrap(~sce.BatchR$Sample)
#ggcells(sce.BatchR, aes(x = MNN_UMAP.1, y = MNN_UMAP.2, colour = Sample)) +geom_point(size = 0.5) +facet_wrap(~ Sample) +labs(x = "PC1", y = "PC2", colour = "Sample")

#Plot UMAP after data integration per joint
plotReducedDim(sce.BatchR, dimred="harmony_UMAP", colour_by="JointLocation") + ggtitle("UMAP after data integration with harmony")+ facet_wrap(~sce.BatchR$JointLocation)

```


## Save the dataset

```{r SaveData}
saveRDS(sce.filtered, file =paste0('/Volumes/Elements/Masterthesis/RA_SingleCellAnalysis/output/','03_sce_Integrated_Harmony.rds'))
```
