---
title: "Clustering"
subtitle: "04_Clustering"
author: "SarahL."
date: "`r format(Sys.time(), '%b %e %Y %H:%M:%S')`"
output: 
  html_document:
    toc: true
    number_sections: true   
    toc_float: true
    code_folding: hide
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Clustering

## Setup

### Load Packages

```{r LoadPackages, warning=FALSE}
#Load Packages

suppressPackageStartupMessages({
library(BiocParallel)
library(ggplot2)
library(dplyr)
library(scater)
library(scran)
library(batchelor)
library(reticulate)
library(bluster)
})

```

### Set params

```{r Setup}
set.seed(100)
bpp <- BiocParallel::MulticoreParam(parallel::detectCores()-1)
path <- "/Volumes/Elements/Masterthesis/RA_SingleCellAnalysis/"
```


## Load Data

```{r LoadDataset}
## RA DATASET
sce.filtered <- readRDS(file = paste0(path,'output/03_sce_Integration_Batchelor.rds'))

```


### Explore dataset

```{r ShowDim}
#Dimensions of count matrix
dim(sce)
```

## Clustering

### Louvain Clustering

```{r}
#Setup Hierarchical Clustering
#use the bluster package

#colData(sce.BatchR)$louvain <- clusterRows(reducedDim(sce.BatchR, "MNN"),TwoStepParam(KmeansParam(centers=1000), NNGraphParam(k=5,cluster.fun="louvain")))
colData(sce.BatchR)$louvain <- clusterCells(sce.BatchR, use.dimred = "MNN", BLUSPARAM = SNNGraphParam(k=15,cluster.fun="louvain"))

table(colData(sce.BatchR)$louvain)


```

```{r}
plotReducedDim(sce.BatchR, dimred="MNN", colour_by="louvain",text_by="louvain") + ggtitle("UMAP with louvain clusters")
plotReducedDim(sce.BatchR, dimred="MNN_UMAP", colour_by="louvain",text_by="louvain") + ggtitle("UMAP with louvain clusters")

```

```{r}
## Silhouette plot

sil.approx <- approxSilhouette(reducedDim(sce.BatchR, "MNN"), clusters=colData(sce.BatchR)$louvain)
sil.approx

sil.data <- as.data.frame(sil.approx)
sil.data$closest <- factor(ifelse(sil.data$width > 0, colData(sce.BatchR)$louvain, sil.data$other))
sil.data$cluster <- colData(sce.BatchR)$louvain

ggplot(sil.data, aes(x=cluster, y=width, colour=closest)) +ggbeeswarm::geom_quasirandom(method="smiley")+ggtitle("Silhouette plot Louvain Clustering")+theme_bw()


```

### Leiden Clustering

```{r}
#Setup Hierarchical Clustering
#use the bluster package

#colData(sce.BatchR)$leiden <- clusterRows(reducedDim(sce.BatchR, "MNN"),TwoStepParam(KmeansParam(centers=100), NNGraphParam(k=5,cluster.fun="leiden")))
colData(sce.BatchR)$leiden <- clusterCells(sce.BatchR, use.dimred = "MNN", BLUSPARAM = SNNGraphParam(k=40,cluster.fun="leiden"))


table(colData(sce.BatchR)$leiden)


```

```{r}
plotReducedDim(sce.BatchR, dimred="MNN", colour_by="leiden",text_by="leiden") + ggtitle("UMAP with leiden clusters")
plotReducedDim(sce.BatchR, dimred="MNN_UMAP", colour_by="leiden",text_by="leiden") + ggtitle("UMAP with leiden clusters")
```

```{r}
## Silhouette plot

sil.approx <- approxSilhouette(reducedDim(sce.BatchR, "MNN"), clusters=colData(sce.BatchR)$leiden)
sil.approx

sil.data <- as.data.frame(sil.approx)
sil.data$closest <- factor(ifelse(sil.data$width > 0, colData(sce.BatchR)$leiden, sil.data$other))
sil.data$cluster <- colData(sce.BatchR)$leiden

ggplot(sil.data, aes(x=cluster, y=width, colour=closest)) +ggbeeswarm::geom_quasirandom(method="smiley")+ggtitle("Silhouette plot leiden Clustering")+theme_bw()
  

```

### Walktrap method

```{r}
#Setup Hierarchical Clustering
#use the bluster package

#colData(sce.BatchR)$walktrap <- clusterRows(reducedDim(sce.BatchR, "MNN"),TwoStepParam(KmeansParam(centers=100), NNGraphParam(k=2,cluster.fun="walktrap")))
colData(sce.BatchR)$walktrap <- clusterCells(sce.BatchR, use.dimred = "MNN", BLUSPARAM = SNNGraphParam(k=20,cluster.fun="walktrap", BPPARAM=bpp))


table(colData(sce.BatchR)$walktrap)


```

```{r}
plotReducedDim(sce.BatchR, dimred="MNN", colour_by="walktrap",text_by="walktrap") + ggtitle("UMAP with walktrap clusters")
plotReducedDim(sce.BatchR, dimred="MNN_UMAP", colour_by="walktrap",text_by="walktrap") + ggtitle("UMAP with walktrap clusters")
```

```{r}
## Silhouette plot

sil.approx <- approxSilhouette(reducedDim(sce.BatchR, "MNN"), clusters=colData(sce.BatchR)$walktrap)
sil.approx

sil.data <- as.data.frame(sil.approx)
sil.data$closest <- factor(ifelse(sil.data$width > 0, colData(sce.BatchR)$walktrap, sil.data$other))
sil.data$cluster <- colData(sce.BatchR)$walktrap

ggplot(sil.data, aes(x=cluster, y=width, colour=closest)) +ggbeeswarm::geom_quasirandom(method="smiley")+ggtitle("Silhouette plot leiden Clustering")+theme_bw()
  

```

## Set clustering to use downstream

```{r}
## Set main clustering for downstream use also as colLabels
##leiden or louvain or walktrap

colData(sce.BatchR)$cluster<- colData(sce.BatchR)$leiden
colLabels(sce.BatchR)<- colData(sce.BatchR)$cluster

```

## Frequencies of cells in clusters per Sample

```{r}
ClusterInfo <- as.data.frame(colData(sce.BatchR)) %>% 
  group_by(cluster, Sample) %>%
  summarise(cells = n(),.groups = 'drop') 

ggplot(data=ClusterInfo, aes(x=Sample,y=cells, fill=cluster)) +
  geom_bar(stat="identity", position="stack") +
  labs(title="Absolute comparison nr Cells in Cluster",subtitle="Per Sample",x="",y="Number of cells")



ggplot(data=ClusterInfo,aes(x=Sample, y=cells, fill=cluster)) +
  geom_bar(stat="identity", position="fill") +
  labs(title="Relative comparison nr Cells in Cluster",subtitle="Per Sample",x="",y="Number of cells")


```


## Save the dataset

```{r SaveData}
saveRDS(sce.filtered, file =paste0('/Volumes/Elements/Masterthesis/RA_SingleCellAnalysis/output/','04_sce_Clustering.rds'))
```
