---
title: "Clustering"
subtitle: "11_CellCycle"
author: "SarahL."
date: "`r format(Sys.time(), '%b %e %Y %H:%M:%S')`"
output: 
  html_document:
    toc: true
    number_sections: true   
    toc_float: true
    code_folding: hide
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
knitr::opts_chunk$set(cache = FALSE, cache.lazy = FALSE)
knitr::opts_chunk$set(dpi = 300, fig.align = "center")
knitr::opts_chunk$set(out.width = "100%", out.height = "100%")
```


# Plotting

## Setup

### Standard packages

```{r LoadPackages, warning=FALSE}
library(here)
source(here("code", "standard_libraries.R"))
```

### Additional Packages

```{r LoadAddPackages, warning=FALSE}
#Load Packages

suppressPackageStartupMessages({
library(Seurat)
})

```


### Set Parameter

```{r Setup}
set.seed(123)
bpp <- BiocParallel::MulticoreParam(parallel::detectCores()-1, RNGseed=123)
path <- here::here()
```


## Load Data

```{r LoadDataset}
## RA DATASET
sce <- readRDS(file = paste0(path,'/output/05_sce_CelltypeAnnotation.rds'))
```

### Explore Dataset

```{r ShowDim}
#Dimensions of count matrix
dim(sce)
```


## Determine Cell cycle

## Define function

```{r LoadDataset}
## RA DATASET
CellCycle <- function(sce)
{
  sce$S.Score <- rep(NA,ncol(sce))
  sce$G2M.Score <- rep(NA,ncol(sce))
  sce$phase <- rep(NA,ncol(sce))
  
  s.genes = cc.genes$s.genes
  g2m.genes = cc.genes$g2m.genes
  so <- Seurat::CreateSeuratObject(as.matrix(counts(sce)))
  so <- Seurat::NormalizeData(so)
  so <- Seurat::FindVariableFeatures(so, selection.method = "vst")
  so <- Seurat::ScaleData(so, features = rownames(so))
  so <- Seurat::CellCycleScoring(so, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
  
  sce$S.Score <- so$S.Score
  sce$G2M.Score <- so$G2M.Score
  sce$phase  <- so$Phase
  return(sce)
}
```




```{r LoadDataset}
## RA DATASET
sce<-CellCycle(sce)
  
```


### PCA

```{r PlotPCAAB2}
#Plot PCA after data integration
plotReducedDim(sce, dimred="MNN_reduced", colour_by="phase") + ggtitle("PCA colored by Cellcycle")
```


### UMAP

```{r PlotUMAPAB1}
#Plot UMAP after data integration
plotReducedDim(sce, dimred="MNN_UMAP_reduced", colour_by="phase") + ggtitle("UMAP colored by Cellcycle")
```

## Frequencies of cellcycle phase per Sample {.tabset}

```{r ClusterInfo}
ClusterInfo <- as.data.frame(colData(sce)) %>% 
  group_by(phase, Sample,Joint.Location) %>%
  summarise(cells = n(),.groups = 'drop') 
```

### Absolute comparison

```{r PlotAbsoluteClustering}

ggplot(data=ClusterInfo, aes(x=Sample,y=cells, fill=phase)) +
  geom_bar(stat="identity", position="stack") +
  labs(title="Absolute comparison nr Cells in Celltype",subtitle="Per Sample",x="",y="Number of cells")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45,hjust=1), axis.ticks.x=element_blank())+

```


### Relative comparison

```{r PlotRelativeClustering}

ggplot(data=ClusterInfo,aes(x=Sample, y=cells, fill=phase)) +
  geom_bar(stat="identity", position="fill") +
  labs(title="Relative comparison nr Cells in celltype",subtitle="Per Sample",x="",y="Number of cells")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45,hjust=1), axis.ticks.x=element_blank())


```



## Frequencies of celltypes in clusters per Condition {.tabset}

```{r ClusterInfo}
ClusterInfo <- as.data.frame(colData(sce)) %>% 
  group_by(phase,Joint.Location) %>%
  summarise(cells = n(),.groups = 'drop') 
```

### Absolute comparison

```{r PlotAbsoluteClustering}

ggplot(data=ClusterInfo, aes(x=Joint.Location,y=cells, fill=phase)) +
  geom_bar(stat="identity", position="stack") +
  labs(title="Absolute comparison nr Cells in Celltype",subtitle="Per Condition",x="",y="Number of cells")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45,hjust=1), axis.ticks.x=element_blank())

```

### Relative comparison

```{r PlotRelativeClustering}

ggplot(data=ClusterInfo,aes(x=Joint.Location, y=cells, fill=phase)) +
  geom_bar(stat="identity", position="fill") +
  labs(title="Relative comparison nr Cells in celltype",subtitle="Per Condition",x="",y="Number of cells")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45,hjust=1), axis.ticks.x=element_blank())+


```


## Save the dataset

```{r SaveData}
saveRDS(sce, file =paste0(path,'/output/11_sce_CellCycle.rds'))
```

