---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

### Project Description

Rheumatoid arthritis is a chronic inflammatory disease where the immune system attacks the synovial lining of the joints. Despite fundamental advances in treatments, a good proportion of patients remain refractory and do not achieve complete remission. Despite the heterogeneity in disease presentation and the diversity of patients affected, rheumatoid arthritis consistently presents itself with a distinctive pattern of joint involvement, varying levels of joint destruction and suggested differences in treatment responses of the joints. Understanding driver of such site- specific differences is crucial for the development of more targeted therapies and enhancing treatment outcomes for rheumatoid arthritis patients.

By leveraging in-house generated single-cell RNA sequencing and spatial transcriptomics datasets, we conducted a comprehensive analysis of 61’242 cells collected from synovial tissue biopsies from a cohort of 17 patients diagnosed with rheumatoid arthritis originating from three different joints affected by the disease (metacarpophalangeal joint, wrist and knee). This investigation led to the identification of 24 specific subsets of synovial cell types and provided insight into their localization within the tissue. We observed differential abundances of the POSTN+ fibroblast subset across joint locations, suggesting a potential proportional difference that could contribute to joint-specific variations and found them to be organized in clusters like aggregates within the synovial tissue.

Focusing on non-infiltrating cells we investigated site-specific transcriptional differences and defined the fibroblasts to be the most dissimilar cell type of the synovium with the identification of HOXD11, HOXD10, HOXC10, SCGB2B2, MSX1, TENM3 and DBN1 as highly concordant differentially expressed genes across the joint locations. Focusing further on the synovial fibroblasts, gene set enrichment analysis identified enriched pathways in the knee and wrist associated with ciliogenesis and enriched pathways in the metacarpophalangeal joint associated with cell adhesion, cell migration, cytoskeleton and extracellular matrix. Additionally, we found enrichment of terms associated with Wnt and TGF-β signaling pathways in the hand joints. Further investigation into cell-cell communication using the inferred spatial organization we implicate the Wnt and TGF-β signaling pathways as potential drivers of site-specific differences in the synovial fibroblasts and macrophages between the joints.
