---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to my Project.


### Table of Contents:


#### Single Cell Data:

- [Data Preparation](00_DataPreparation.html)
- [Quality Control](01_QualityControl.html)
- [Dimensionality Reduction](02_DimensionalityReduction.html)
- [Integration](03_Integration_Batchelor.html)
- [Cellcycle Assignement](04_CellCycle.html)
- [Clustering](05_Clustering.html)
- [Annotation](06_CelltypeAnnotation.html)
- [Subclustering](07_SubClustering.html)
- [Subcluster Annotation](07_SubClustering_Annotation.html)
- [Subcluster Merge](07_SubClustering_Merge.html)



#### Spatial Transcriptomics Data:

- [Spatial Knee](Spatial_Knee.html)
- [Spatial Hand](Spatial_Hand.html)



#### Analysis

- [Differential Abundance](09_DifferentialAbundance_miloR.html)
- [Differential Expression MAST](08_DifferentialExpression_MAST.html)
- [Differential Expression Pseudobulk](08_DifferentialExpression_Pseudobulk.html)
- [Enrichmennt Analysis](10_EnrichmentAnalysis.html)
- [Cell-Cell Communication](11_CellChat.html)



